# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

%YAML 1.1
---
gui:
  nerdFontsVersion: "3"

git:
  autoFetch: false

quitOnTopLevelReturn: true
keybinding:
  universal:
    quit: '<c-q>'
