#!/bin/sh

# Force tmux to start in 256 color mode
alias tmux='tmux -2'
alias tmxa='tmux attach -d -t'

# Pretty print the path
alias path='echo $PATH | tr -s ":" "\n"'

mcd() { mkdir -p "$1" && cd "$1"; }

# Include custom aliases
if [[ -f $HOME/.aliases.local ]]; then
    source ~/.aliases.local
fi

# Predictable SSH authentication socket location.
SOCK="/tmp/ssh-agent-$USER-screen"
if test $SSH_AUTH_SOCK && [ $SSH_AUTH_SOCK != $SOCK ]
then
    rm -f /tmp/ssh-agent-$USER-screen
    ln -sf $SSH_AUTH_SOCK $SOCK
    export SSH_AUTH_SOCK=$SOCK
fi

function fixtmux() {
    eval $(tmux show-env -s)
}

