#!/bin/sh

# Force tmux to start in 256 color mode
alias tmux='tmux -2'
alias tmxa='tmux attach -d -t'
alias tmxn='tmux new-session -s'

# Pretty print the path
alias path='echo $PATH | tr -s ":" "\n"'
alias ls='ls --color'

mcd() { mkdir -p "$1" && cd "$1"; }

# Include custom aliases
if [[ -f $HOME/.aliases.local ]]; then
    source ~/.aliases.local
fi

function run_realpath() {
    local exe=$1
    shift 1
    local args=()
    for i in $@; do
        if [[ -h $i ]]; then
            args+=$(realpath $i)
        else
            args+=$i
        fi
    done

    command $exe -p "${args[@]}"
}

alias vi="run_realpath vi"
alias vim="run_realpath vim"
alias nvim="run_realpath nvim"
alias gvim="run_realpath gvim"

function fixtmux() {
    eval $(tmux show-env -s)
}

function update_ssh_sock()
{
    # Predictable SSH authentication socket location.
    local SOCK=~/.ssh/ssh_auth_sock
    if test "$SSH_AUTH_SOCK" && [ $SSH_AUTH_SOCK != $SOCK ]
    then
        rm -f $SOCK
        ln -sf $SSH_AUTH_SOCK $SOCK
        export SSH_AUTH_SOCK=$SOCK
    fi
}

update_ssh_sock
