#!/usr/bin/env bash

set -e

CONFIG="dotbot.conf.yaml"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTBOT_DIR="$BASEDIR/dotbot"
DOTBOT_BIN="$DOTBOT_DIR/bin/dotbot"

PLUGIN_DIR="$BASEDIR/plugins"

git -C "${DOTBOT_DIR}" submodule sync --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${DOTBOT_BIN}" \
    -d "${BASEDIR}" \
    -p $PLUGIN_DIR/dotbot-sync/sync.py \
    -c "${CONFIG}" "${@}"
