#!/usr/bin/env bash

CONFIG="deploy/dotbot.conf.yaml"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

DOTBOT_DIR="$BASEDIR/dotbot"
PLUGIN_DIR="$BASEDIR/plugins"

DOTBOT_BIN="$DOTBOT_DIR/bin/dotbot"

PLUGINS="dotbot-sync dotbot-brew"
echo "Plugins: $PLUGINS"

cd "${BASEDIR}"
git submodule update --init --recursive --quiet $DOTBOT_DIR $PLUGIN_DIR

DOTBOT_ARGS=
for p in $PLUGINS; do
	DOTBOT_ARGS+=" --plugin-dir $PLUGIN_DIR/$p"
done
echo "Args: $DOTBOT_ARGS"

"${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" $DOTBOT_ARGS "${@}"

if [[ "$OSTYPE" = "darwin"* ]]; then
    echo
    echo "Running mac specific configuration..."

    "${DOTBOT_BIN}" -d "${BASEDIR}" -c deploy/mac.conf.yaml $DOTBOT_ARGS "${@}"
fi

