#!/bin/sh

# Necessary to make chrome pick up the proxy settings stored in gconf.
export DESKTOP_SESSION=cinnamon  # gnome for trusty.

# NOTE: This may break your compose key.
# See http://g/i3-users/YBexXGbik7E for more details.
export GTK_IM_MODULE=xim

# Desktop background color.
xsetroot -solid "#333333"

# TODO: may be needed only on laptops
xinput --set-prop "SynPS/2 Synaptics TouchPad" "libinput Natural Scrolling Enabled" 1

## Uncomment if you use urxvt terminal emulator.
## Start urxvtd
urxvtd -q -f -o
export TERMINAL=urxvtc
