#!/bin/sh

# Force tmux to start in 256 color mode
alias tmux='tmux -2'
alias tmxa='tmux attach -d -t'
alias tmxn='tmux new-session -s'

alias vsc-restart='systemctl --user restart code-server'

# Pretty print the path
alias path='echo $PATH | tr -s ":" "\n"'

mcd() {
  mkdir -p "$1" && cd "$1" || return
}

# Include custom aliases
if [ -f "$HOME/.aliases.local" ]; then
    source "$HOME/.aliases.local"
fi

rrr() {
    local exe=$1
    shift 1
    local args=()
    for i in $@; do
        if [[ -h $i ]]; then
            args+=$(realpath $i)
        else
            args+=$i
        fi
    done

    command $exe "${args[@]}"
}

dirdiff()
{
    # Shell-escape each path:
    DIR1=$(printf '%q' "$1"); shift
    DIR2=$(printf '%q' "$1"); shift
    vim $@ +DirDiff $DIR1 $DIR2
}

fixtmux() {
    eval $(tmux show-env -s)
}

update_ssh_sock()
{
    # Predictable SSH authentication socket location.
    SOCK=~/.ssh/ssh_auth_sock
    if test "$SSH_AUTH_SOCK" && [ $SSH_AUTH_SOCK != $SOCK ]
    then
        rm -f $SOCK
        ln -sf $SSH_AUTH_SOCK $SOCK
        export SSH_AUTH_SOCK=$SOCK
    fi
}

# update_ssh_sock
