- defaults:
    link:
        relink: true
        relative: true
        create: true
        force: true
    sync:
        rsync: 'rsync'                        # rsync executable to be used
        options: ['--delete', '--safe-links'] # list of options for rsync
        create: false                         # create missing directory hierarchy
        stdout: false                         # ignore stdout of rsync process
        stderr: false                         # ignore stderr of rsync process

- clean: ['~', '~/nano.d', '~/.local/bin', '~/.config.nvim']

- link:
    ~/.ackrc:
    ~/.aliases:
    ~/.agignore:
    ~/.bash: bash
    ~/.bash_aliases: bash/bashrc
    ~/.ctags:
    ~/.curlrc:
    ~/.config/nvim/autoload: vim/autoload
    ~/.config/nvim/init.vim: vim/init.vim
    ~/.config/oni/config.tsx: oni/config.tsx
    ~/.config/oni/.editorconfig: oni/editorconfig
    ~/.gitattributes: git/gitattributes
    ~/.gitconfig: git/gitconfig
    ~/.gitignore: git/gitignore
    ~/.gitk: git/gitk
    ~/.gvimrc: vim/gvimrc
    ~/.local/bin:
        glob: true
        path: bin/*
    ~/.nanorc: nano/nanorc
    ~/.nano.d/syntax-highlighting: nano/syntax-highlighting
    ~/.pythonrc: python/pythonrc
    ~/.pylintrc: python/pylintrc
    ~/.screenrc:
    ~/.ssh/rc: ssh/rc
    ~/.tmux: tmux
    ~/.tmux.conf: tmux/tmux.conf
    ~/.vim: vim
    ~/.vimrc: vim/init.vim
    ~/.wgetrc:
    ~/.zsh: zsh
    ~/.zshenv: zsh/zshenv
    ~/.zshprofile: zsh/zshenv
    ~/.zprofile: zsh/zprofile
    ~/.zshrc: zsh/zshrc

- sync:
    ~/.tmux.design.conf: tmux/design.conf

- shell:
    - [git submodule update --init --recursive, Installing submodules]
    - [vim +PlugInstall +qall, Installing Vim Plugins]

