- defaults:
    link:
        relink: true
        relative: true
        create: true
        force: true
    sync:
        rsync: 'rsync'                        # rsync executable to be used
        options: ['--delete', '--safe-links'] # list of options for rsync
        create: false                         # create missing directory hierarchy
        stdout: false                         # ignore stdout of rsync process
        stderr: false                         # ignore stderr of rsync process

- clean: [
    '~',
    '~/.nano.d',
    '~/.local/bin',
    '~/.config',
    '~/.config/oni',
    '~/.config/nvim'
  ]

- link:
    ~/.ackrc:
    ~/.aliases:
    ~/.agignore:
    ~/.bash:
    ~/.bash_aliases: bash/bashrc
    ~/.ctags:
    ~/.curlrc:
    ~/.config/nvim/autoload: vim/autoload
    ~/.config/nvim/init.vim: vim/init.vim
    ~/.config/oni/config.tsx: oni/config.tsx
    ~/.config/oni/.editorconfig: oni/editorconfig
    ~/.gitattributes: git/gitattributes
    ~/.gitconfig: git/gitconfig
    ~/.gitignore: git/gitignore
    ~/.gitk: git/gitk
    ~/.gvimrc: vim/gvimrc
    ~/.local/bin:
        glob: true
        path: bin/*
    ~/.nanorc: nano/nanorc
    ~/.nano.d/syntax-highlighting: nano/syntax-highlighting
    ~/.profile:
    ~/.pythonrc: python/pythonrc
    ~/.pylintrc: python/pylintrc
    ~/.ripgreprc:
    ~/.screenrc:
    ~/.ssh/rc: ssh/rc
    ~/.tmux:
    ~/.tmux.conf: tmux/tmux.conf
    ~/.vim:
    ~/.vimrc: vim/init.vim
    ~/.wgetrc:
    ~/.zsh:
    ~/.zshenv: zsh/zshenv
    ~/.zshprofile: zsh/zshenv
    ~/.zprofile: zsh/zprofile
    ~/.zshrc: zsh/zshrc


- sync:
    ~/.tmux.design.conf: tmux/design.conf

- if:
    os: darwin
    actions:
        clean: ['~/Library/Fonts']
        sync:
            ~/Library/Fonts/MyFonts: fonts
        brew:
            - rsync
            - the_silver_searcher
            - ctags

# Simple packages that don't have X/wm dependency
- if:
    os: linux
    actions:
        apt:
            - build-essential
            - exuberant-ctags
            - neovim
            - rsync
            - ruby
            - silversearcher-ag
            - tmux
            - vim
            - zsh

# Packages needed when X is available
- if:
    and:
        os: linux
        shell: [ test -n "$(command -v X)" ]
    actions:
        clean: ['~/.local/share/fonts']
        link:
            ~/.config/compton.conf:
            ~/.config/dunst:
            ~/.config/i3:
            ~/.config/i3status:
            ~/.config/rofi:
            ~/.local/share/fonts:
                glob: true
                path: fonts/*
            ~/.urxvt:
            ~/.xsessionrc:
            ~/.xsettingsd:
            ~/.Xresources:
        shell:
            - [ test -z "$(command -v fc-cache)" || fc-cache -f ~/.local.share.fonts ]
        apt:
            - compton
            - dex
            - fonts-font-awesome
            - i3
            - mate-power-manager
            - rofi
            - scrot
            - viewnior
            - volumeicon-alsa
            - xbacklight
            - xinput
            - xsecurelock
            - xsettingsd
            - xss-lock

# Gnome settings if dconf is installed
- if:
    and:
        os: linux
        shell: [ test -n "$(command -v dconf)" ]
    actions:
        link:
            ~/.config/dconf:
        shell:
            - [cat ~/.config/dconf/user.d/* | dconf load /, Loading dconf configurations]

- shell:
    - [git submodule update --init --recursive, Installing submodules]
    - [vim +PlugInstall +qall, Installing Vim Plugins]

