#!/bin/sh

NERD_FONTS="
    AnonymousPro
    RobotoMono
    SourceCodePro
"

sudo apt-get update

# Terminal
sudo apt-get install -y tmux zsh

# Editors
sudo apt-get install -y vim neovim

# Development
sudo apt-get install -y cmake

# Source navigation
sudo apt-get install -y exuberant-ctags silversearcher-ag

if [ -n "$NERD_FONTS" ]; then
    TMPDIR=$(mktemp -d)
    git clone https://github.com/ryanoasis/nerd-fonts $TMPDIR/nerd-fonts
    for f in $NERD_FONTS; do
        $TMPDIR/nerd-fonts/install.sh $f
    done
fi
