name: Dotfiles CI

on:
  push:
  pull_request:

jobs:
  clone-and-install:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Install
        run: ./install.sh
      - name: Chezmoi data
        run: '"$HOME/.local/bin/chezmoi" data'
